### PR TITLE
Initial quarto project

### PR DESCRIPTION
**Pull request by CGMossa**
Let's warm up with a PR that.. just gets stuff starting.

### CODE REVIEW

**Comment by JosiahParry** [comment]
This looks to be missing the actual quarto files. Can you include thosE?

**Comment by CGMossa** [comment]
I think `git` ate my files again. I had to do some backupping because I accidentally pushed to main. I can't push to `main`anymore. I'm unsure if we need to include all files or some. I'd love advice.

**Comment by JosiahParry** [comment]
Looks like this is still missing the `.qmd` files

**Comment by CGMossa** [comment]
@kbvernon @JosiahParry Alright. I'm not doing anymore in this PR. It sets up a basic quarto page.
You're more than welcome to ask for things, otherwise, let's approve and merge. And work on some outlines in an issue or two.

**Review by JosiahParry — APPROVED** [review]
lgtm lets get rollin

**Comment by CGMossa** [comment]
I removed the signed commits requirements. I don't know why my commits didn't fulfil this.
The GHA script works, so all in all, this works as a starting point.

**Pull request merged**
